theme: jekyll-theme-minimal
title: Deep Learning for Organic Chemistry
description: > # your text below (remove <br> elements if you don't need line breaks)
  [Utilizing Deep Learning Techniques to Identify Chemical Structures]
  <br>
  <br>
  <a href="https://cwolfbrandt.github.io">Return to Portfolio</a>
  <br>
theme: jekyll-theme-minimal
