theme: jekyll-theme-minimal
title: Deep Learning for Organic Chemistry
description: [Utilizing Deep Learning Techniques to Identify Chemical Structures]
linkedin: carly-wolfbrandt

<a href="https://www.cwolfbrandt.github.io">Return to Portfolio</a>
