theme: jekyll-theme-minimal
title: Deep Learning for Organic Chemistry
description: [Utilizing Deep Learning Techniques to Identify Chemical Structures]
linkedin: carly-wolfbrandt
  <br>
  <br>
  <a href="https://www.cwolfbrandt.github.io">Return to Portfolio</a>
