theme: jekyll-theme-minimal
title: Deep Learning for Organic Chemistry
description: [Utilizing Deep Learning Techniques to Identify Chemical Structures]
  <br>
  <br>
  <a href="https://www.cwolfbrandt.github.io">Return to Portfolio</a>
  <br>
  <a href="https://www.linkedin.com/in/carly-wolfbrandt/">View My LinkedIn Profile</a>
